version: '3'

services:
   pythonapp:
      image: all-python3.6:latest
      ports:
        - 5000:5000
      volumes:
        - /opt/python/scripts:/opt/data:Z
      networks:
         allash:
            ipv4_address: 10.100.0.1
      deploy:
        replicas: 2
        resources:
            limits:
               cpus: '0.01'
               memory: 50M
      depends_on:
        - redis
   redis:
      image: redis
      deploy:
        replicas: 2
        resources:
            limits: 
               cpus: '0.01'
               memory: 50M
      networks:
         allash:
             ipv4_address: 10.100.0.2     

networks:
  allash:
     ipam:
       driver: default
       config:
         - subnet: 10.100.0.0/24
